### ISSUE TITLE
[CLOSED] Programally close Notification

### ISSUE THREAD

**Issue by valms** [DragShot/DS-Desktop-Notify#1]
I read the code but i didn't get programally close (on frame close) the notification frame. Howcan i achiev this?

**Comment by DragShot** [comment]
I've replied to your mail with a workaround. Also, I'll be pushing an update soon with a permanent solution for this. Just let me test if it works as intended first.

**Comment by DragShot** [comment]
Alright, I've added a proper method for this. You can now use `hide()` in your window event handler in order to hide your notification.

**Comment by valms** [comment]
Hello Drag! I'll test the solution and then bring the feedback. =]

**Comment by valms** [comment]
Hello! Doesn't work :/

I have this code:

                      `this.addComponentListener( new ComponentListener() {
			NotificationBuilder notificationBuilder = null;
			
			@Override
			public void componentResized(ComponentEvent e) {
			
			}
			
			@Override
			public void componentMoved(ComponentEvent e) {
			
			}
			
			@Override
			public void componentShown(ComponentEvent e) {
				//http://dscore.webcindario.com/software/desktopnotify.php
				//if (notificationBuilder == null) {
				notificationBuilder = new NotificationBuilder();
				notificationBuilder.setTheme( NotifyTheme.Light )
					.setTitle( "-Title-" )
					.setMessage( "-Messag-" )
					.setType( DesktopNotify.WARNING )
					.setIcon( ApplicationUtils.ICON_BUFFERED_IMAGE );
				notificationBuilder.build().show();
				//}
				toFront();
				setAutoRequestFocus( true );
			}
			
			@Override
			public void componentHidden(ComponentEvent e) {
				notificationBuilder.build().hide();
			}
		} );`

**Comment by DragShot** [comment]
I can see you're saving the builder, but each time you call `build()` you're actually creating a new `DesktopNotify` object. You need to save the result of `build()` in order to call `hide()` from that object later.

```java
DesktopNotify notif;
[...]
public void componentShown(ComponentEvent e) {
[...]
    notif = notificationBuilder.build();
    notif.show();
[...]
}
public void componentHidden(ComponentEvent e) {
    notif.hide();
}
```

Try and see if this helps.

**Comment by valms** [comment]
worked like a charm! Thank you <3 =]
